### ISSUE TITLE
It would be nice to be able to customize shortcut keys.

### ISSUE THREAD

**Issue by ghost** [dwrdx/mywords.nvim#1]
It would be nice to be able to customize shortcut keys.

**Comment by junnplus** [comment]
@dimosz It's very simple, just copy follow code to your lua config and change map key.
https://github.com/dwrdx/mywords.nvim/blob/main/lua/mywords.lua#L86-L96

**Comment by dimosz** [comment]
@dwrdx 
I have mapped the shourtcut to leader + h/H. It's a bit wasteful to take two keys.
Thanks for your work and reply.

**Comment by dimosz** [comment]
> @dimosz It's very simple, just copy follow code to your lua config and change map key. https://github.com/dwrdx/mywords.nvim/blob/main/lua/mywords.lua#L86-L96

**Comment by ghost** [comment]
@Junnplus Thanks for your reply.

**Comment by dwrdx** [comment]
@dimosz  alternatively, if you are using init.vim to configure your nvim, you can use following setup:
```
map <silent> <leader>m  :lua require'mywords'.hl_toggle()<CR>
map <silent> <leader>c :lua require'mywords'.uhl_all()<CR>
```
I just updated this to readme, and will close this ticket.
