### ISSUE TITLE
When splitting a window, the highlighting does not take effect globally.

### ISSUE THREAD

**Issue by Virus-V** [dwrdx/mywords.nvim#2]
Hi! This is a very helpful Vim plugin, thank you.

But when I used it, I encountered some problems, maybe I used it incorrectly?

When the screen is split, highlight a word in the original panel, but it will not take effect in the new panel. 

However, after highlighting a word in the new panel, and then highlighting the word in any panel, both panels will take effect.

![Capture_01](https://user-images.githubusercontent.com/32447708/156914167-f01e60d6-f459-4967-bda1-5bb8950b813b.PNG)

How to fix this problem please? Thanks!

**Comment by dwrdx** [comment]
Hi @Virus-V, thank you for reporting this issue. This is a bug, I have already fixed It. Please pull the latest code and try.
