### ISSUE TITLE
Add an option to pass a word for highlight

### ISSUE THREAD

**Issue by justrajdeep** [dwrdx/mywords.nvim#5]
hi there,

Can you please add an option to pass a word/regex to highlight instead of the exact word under the cursor?

TIA.

**Comment by dwrdx** [comment]
@justrajdeep this is a really good idea, I've done this with a quick update. You and update and use the following key mapping
`map <silent> <leader>r :lua require'mywords'.hl_toggle_regex()<CR>`

**Comment by justrajdeep** [comment]
Thanks @dwrdx  for this fix. Really appreciate it.
